services:
  backend:
    build: ./backend
    container_name: videoapp-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    container_name: videoapp-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: npm run dev